return {
  "github/copilot.vim",
  config = function()
    vim.g.copilot_filetypes = {
      ["*"] = false,
      clojure = true,
      cmake = true,
      cpp = true,
      css = true,
      c = true,
      dockerfile = true,
      gitcommit = true,
      go = true,
      haskell = true,
      html = true,
      h = true,
      javascriptreact = true,
      javascript = true,
      java = true,
      json = true,
      jsx = true,
      lisp = true,
      lua = true,
      make = true,
      nix = true,
      python = true,
      rust = true,
      shell = true,
      sh = true,
      sql = true,
      toml = true,
      typescript = true,
      vim = true,
      yaml = true,
    }
  end,
}
